name: Keep Streamlit Alive

on:
  schedule:
    - cron: '0 */12 * * *'  # every 12 hours
  workflow_dispatch:

jobs:
  wake_app:
    runs-on: ubuntu-latest
    steps:
      - name: Wake GitHub Self-Analysis App
        run: |
          curl -L --max-time 60 \
          "https://app-self-analysis.streamlit.app/" \
          -H "User-Agent: Mozilla/5.0"
          echo "App pinged successfully"
